
var obj = {
 "result":1,
 "message":"请求班级信息成功",
 "data":{
	"first":[
 		{"name":"孔令峰"},
 		{"name":"张华鑫"},
 		{"name":"黄青清"},
 		{"name":"向家钰"},
 		{"name":"唐辉"},
 		{"name":"张冠廷"},
 		{"name":"黄烁"}
 	 ],
 	"second":[
 		{"name":"杨科"},
 		{"name":"李志强"},
 		{"name":"张豆"},
 		{"name":"汤慧超"},
 		{"name":"李哲伟"},
 		{"name":"杨科"},
 		{"name":"乔洋"}
 	],
 	"third":[
 		{"name":"王静娜"},
 		{"name":"齐学全"},
 		{"name":"卢红娟"},
 		{"name":"张晨曦"},
 		{"name":"邓小琴"},
 		{"name":"王晓敏"},
 		{"name":"王久远"}
 	],
 	"fourth":[
 		{"name":"王建贵"},
 		{"name":"邹有力"},
 		{"name":"张江"},
 		{"name":"李虹"},
 		{"name":"王宇"},
 		{"name":"夏绍勇"},
 		{"name":"程伟杰"}
 	],
 	"class":["91班","92班","93班"],
 	"group":["1组","2组","3组","4组"],
	 "grade":["CEO","CEO","组长","组员"]
 }

}

jsonpcallback(obj);